import React from 'react'

const About = () => {
    return (
        <div style={{height: '50vh'}}>
            <h2>sdadsaasd</h2>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Assumenda nihil pariatur nisi, inventore dolore harum explicabo repudiandae nulla aliquam sit fuga officiis dolorum itaque sequi omnis, vitae commodi placeat, maxime sed beatae? Reprehenderit aut totam illo quasi ratione error? Optio cupiditate dicta, non fugiat amet dignissimos aut tempora delectus expedita.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Earum hic provident officia doloremque odit cum officiis esse! Ipsa repudiandae deleniti officiis aperiam ad fugit ut eius voluptatem, iste blanditiis autem id. Tenetur repudiandae asperiores sapiente exercitationem ipsam natus in dolore autem omnis sunt aperiam expedita quo voluptate qui vitae saepe, voluptates quibusdam, cum sed commodi. Eum, dicta harum. Molestias, totam harum dolorem fuga unde sit rerum. Possimus illo aut blanditiis placeat nobis officiis reiciendis officia ut tempore cumque, quasi non sed nihil? Aliquid quod assumenda excepturi nobis sit hic vitae ut sapiente odio quia ipsam eius quis et, molestias vero culpa fuga fugiat quaerat itaque aperiam ipsa at placeat fugit? Eaque, debitis doloremque. Necessitatibus optio laudantium adipisci reiciendis enim quod temporibus, quidem eveniet neque!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae, distinctio nobis dolorem, rerum autem tenetur ea blanditiis velit officiis, quibusdam incidunt voluptatum? Corporis ad repellat qui facere? Doloribus distinctio quis voluptas quasi aliquid eos optio, eveniet quia at tenetur recusandae magnam deserunt consequatur quas consectetur, incidunt esse autem amet minus adipisci quae fuga tempore corrupti! Eaque aut iure in dicta odit ad ducimus inventore, animi assumenda alias, sit pariatur, minima architecto soluta? Esse libero qui omnis in tempora quos unde totam nesciunt officia. Dolore architecto, culpa dolores adipisci repellat saepe eos odio ratione quasi libero et itaque, consectetur minima velit tempora cupiditate laboriosam. Deserunt aliquid quisquam debitis reprehenderit esse, ea animi vitae nobis accusantium perferendis. Sapiente, vitae, laborum magnam culpa facilis est sequi velit, beatae voluptatum accusamus similique. Error fugiat eius laborum deleniti eaque quae dolore qui nihil maiores perferendis expedita debitis esse placeat praesentium eligendi tenetur architecto deserunt doloremque velit id assumenda, nemo, vero facilis temporibus. Aut consectetur quis unde quo optio ab molestiae commodi doloribus nostrum voluptates? Debitis, temporibus? Aut, adipisci pariatur nostrum consequatur saepe sequi architecto neque veritatis quaerat omnis, dolorem, ipsam quis libero sed velit alias quo quod! Dolor ut molestiae hic aut at deleniti adipisci.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae, distinctio nobis dolorem, rerum autem tenetur ea blanditiis velit officiis, quibusdam incidunt voluptatum? Corporis ad repellat qui facere? Doloribus distinctio quis voluptas quasi aliquid eos optio, eveniet quia at tenetur recusandae magnam deserunt consequatur quas consectetur, incidunt esse autem amet minus adipisci quae fuga tempore corrupti! Eaque aut iure in dicta odit ad ducimus inventore, animi assumenda alias, sit pariatur, minima architecto soluta? Esse libero qui omnis in tempora quos unde totam nesciunt officia. Dolore architecto, culpa dolores adipisci repellat saepe eos odio ratione quasi libero et itaque, consectetur minima velit tempora cupiditate laboriosam. Deserunt aliquid quisquam debitis reprehenderit esse, ea animi vitae nobis accusantium perferendis. Sapiente, vitae, laborum magnam culpa facilis est sequi velit, beatae voluptatum accusamus similique. Error fugiat eius laborum deleniti eaque quae dolore qui nihil maiores perferendis expedita debitis esse placeat praesentium eligendi tenetur architecto deserunt doloremque velit id assumenda, nemo, vero facilis temporibus. Aut consectetur quis unde quo optio ab molestiae commodi doloribus nostrum voluptates? Debitis, temporibus? Aut, adipisci pariatur nostrum consequatur saepe sequi architecto neque veritatis quaerat omnis, dolorem, ipsam quis libero sed velit alias quo quod! Dolor ut molestiae hic aut at deleniti adipisci.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae, distinctio nobis dolorem, rerum autem tenetur ea blanditiis velit officiis, quibusdam incidunt voluptatum? Corporis ad repellat qui facere? Doloribus distinctio quis voluptas quasi aliquid eos optio, eveniet quia at tenetur recusandae magnam deserunt consequatur quas consectetur, incidunt esse autem amet minus adipisci quae fuga tempore corrupti! Eaque aut iure in dicta odit ad ducimus inventore, animi assumenda alias, sit pariatur, minima architecto soluta? Esse libero qui omnis in tempora quos unde totam nesciunt officia. Dolore architecto, culpa dolores adipisci repellat saepe eos odio ratione quasi libero et itaque, consectetur minima velit tempora cupiditate laboriosam. Deserunt aliquid quisquam debitis reprehenderit esse, ea animi vitae nobis accusantium perferendis. Sapiente, vitae, laborum magnam culpa facilis est sequi velit, beatae voluptatum accusamus similique. Error fugiat eius laborum deleniti eaque quae dolore qui nihil maiores perferendis expedita debitis esse placeat praesentium eligendi tenetur architecto deserunt doloremque velit id assumenda, nemo, vero facilis temporibus. Aut consectetur quis unde quo optio ab molestiae commodi doloribus nostrum voluptates? Debitis, temporibus? Aut, adipisci pariatur nostrum consequatur saepe sequi architecto neque veritatis quaerat omnis, dolorem, ipsam quis libero sed velit alias quo quod! Dolor ut molestiae hic aut at deleniti adipisci.</p>
        </div>
    )
}

export default About
